### ISSUE TITLE
📃New Blog Post - Add news blog

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#19]
### Description

Add a new blog to the site for news.

Also, post a blog about the funding news with **_Open Collective_**.

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
