### ISSUE TITLE
♻️Create news post scripts

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#23]
### Complete The Item Below

- [X] I have updated the title without removing the ♻️ emoji.

### Description

Create scripts to automatically create a new news blog post about a release. These scripts will automatically create a folder with the correct date stamp and name and the `index.mdx` page with its content.

Various parts of the post page will have injection points to inject information from another system. A _**deno deploy endpoint**_will build this page.

> [!Warning]
> This deno deploy endpoint still needs to be constructed.

This issue will use that endpoint to build and return the page content. This new deno deploy endpoint will also be used to create templates for tweets, announcements, and more.

### **CICD:**

Create a new release workflow to perform release news posts. This workflow needs to be executed by a GitHub API call. For example, this will allow **_Velaptor_** to execute the workflow after a release has been performed. This will make it super easy to post news updates that a release was performed by a KInsonDigital org project.

The workflow will use the scripts to be able to generate the new folder and page files as well as call the deno deploy endpoint to do the work.

### Acceptance Criteria

- [ ] Auto-release news post scripts created
- [ ] Release workflow updated to be invoked by API calls

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue closed due to effort involved not being worth the outcome.
