### ISSUE TITLE
⚙️Setup site to have a social media preview

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#25]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Set up the website to have a social media preview just like Velaptor docs.

Use Velaptor docs as a reference.

### Acceptance Criteria

- [x] Social media preview set up

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
