### ISSUE TITLE
📃New Blog Post - Tauri front end debugging in VSCode

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#27]
### Description

Create a blog post about how to set up debugging in **VSCode** for Tauri applications.

Notes on how to set this up can be found in the personal **Obsidian** vault.

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
