### ISSUE TITLE
📃New Blog Post - TEST ISSUE

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#29]
### Description

THIS IS FOR TESTING

### ToDo Items

- [ ] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
