### ISSUE TITLE
⚙️Fix base url issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#4]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Fix an issue with the base URL not being configured based on the default URL setup by GitHub pages.

### Acceptance Criteria

- [x] Base URL issue fixed

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
