### ISSUE TITLE
⚙️Migrate from yarn to pnpm

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#44]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Migrate the current package management system of _**yarn**_ to _**pnpm**_.

**Additional Info:**
- [pnpm docs](https://pnpm.io/)
- [Migration Guide](https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04)

### **Follow these steps to migrate:**
Sure, here are the steps to migrate from Yarn to PNPM for a Docusaurus website:

1. **Install PNPM**: You can install PNPM globally using npm with the command `npm install -g pnpm`¹.
1. **Delete node_modules**: You can use `npx npkill` to delete the `node_modules` directory¹.
    1. **Add to package.json**: Add the following to your `package.json` file under "scripts": `{ "preinstall": "npx only-allow pnpm" }`. 
    > **Note**
    > This will prevent other developers from accidentally installing dependencies with anything other than PNPM¹.
1. **Run `pnpm import`**: This command will create a `pnpm-lock.yaml` file based on `yarn.lock`¹.
1. **Remove yarn.lock**: Remove the `yarn.lock` file from your project¹.
1. **Install dependencies**: Run `pnpm i` to install the dependencies¹.
1. **Replace `yarn` with `pnpm`**: Replace all instances of `yarn` with `pnpm` in all `package.json` and other files. For example, change `yarn test` to `pnpm test`¹.

Please note that PNPM doesn't use dependency hoisting by default. If you have a package A that imports a package B but doesn’t explicitly specify B in the `dependencies` or `devDependencies`, then the execution will fail.

Here is a code block that shows the changes in `package.json`:
```json
{
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    ...
  },
  ...
}
```

### **Update NPM Scripts:**
Also, update the npm scripts in the _**package.json**_ to use `pnpm` instead of `yarn`.
```diff
  "scripts": {
    "docusaurus": "docusaurus",
-    "start": "docusaurus start",
+    "start": "pnpm i && docusaurus start",
-   "build": "docusaurus build",
+    "build": "pnpm i && docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids",
    "typecheck": "tsc",
    "clean": "@powershell Remove-Item .\\node_modules -Force -Recurse",
    "preinstall": "npx only-allow pnpm"
  },
```

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] `yarn` removed from the project
- [x] `pnpm` added to the project
- [x] The _**release.yml**_ workflow updated to use `pnpm`
- [x] The _**build-status-check.yml**_ workflow updated to use `pnpm`
```

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
