### ISSUE TITLE
♻️Setup release workflow to do dry runs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#50]
### Complete The Item Below

- [X] I have updated the title without removing the ♻️ emoji.

### Description

Set up the release workflow to perform dry runs.  This is good for running the majority of the release workflow for testing purposes without doing an actual release.

### Acceptance Criteria

- [x] Release workflow updated to perform dry runs

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
