### ISSUE TITLE
⚙️Update issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#51]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Update all of the issue templates to use the GitHub task list feature for the acceptance criteria

### Acceptance Criteria

- [ ] Issue templates updated

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
