### ISSUE TITLE
📃New Blog Post - Perf improvements for Velaptor v1.0.0-preview.31

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#57]
### Description

Create a blog post about the performance gains made with the keyboard input functionality in Velaptor v1.0.0-preview.31 release.

1. Highlight the improvement gains with charts
2. Explain how some of these improvements were done

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
