### ISSUE TITLE
⚙️Setup social preview

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#6]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Set up the social preview part of the website.  This is a docusaurus thing. Look into **VelaptorDocs** and the docusuarus docs on how to do this.

### Acceptance Criteria

- [x] Social preview setup

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
