### ISSUE TITLE
⚙️Perform various improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#7]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Perform various improvements such as workflows, readme, ide settings, etc.

### Acceptance Criteria

- [x] Improvements made

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
[run-sync]
