### ISSUE TITLE
📃New Blog Post - CASL Release v1.0.0-preview.18

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#71]
### Description

Create a blog post about the new release for CASL _**v1.0.0-preview.18**_

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
