### ISSUE TITLE
📃New Blog Post - Velaptor Release v1.0.0-preview.35

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#73]
### Description

Create a new release news blog post for Velaptor _**v1.0.0-preview.35**_

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Acceptance Criteria
```[tasklist]
- [ ] New blog post issue template updated to include acceptance criteria
- [ ] Main headings all updated with blue color that matches table of contents color
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
