### ISSUE TITLE
📝Fix spelling and grammar issues

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/blog#76]
### Complete The Item Below

- [X] I have updated the title without removing the 📝 emoji.

### Description

Fix spelling and grammar issues and broken URL

### Acceptance Criteria

asdf

### ToDo Items

- [x] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
