### ISSUE TITLE
📝asdf

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/blog#78]
### Complete The Item Below

- [X] I have updated the title without removing the 📝 emoji.

### Description

asdf

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
```

### ToDo Items

- [ ] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
