### ISSUE TITLE
📃New Blog Post - Velaptor v1.0.0-preview.36 Release

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#81]
### Description

Create a blog post about the release of Velaptor v1.0.0-preview.36

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] Blog post created
- [x] Grammar and any spelling issues checked for and fixed
```

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
