### ISSUE TITLE
⚙️Set up tailwind css

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#86]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Set up tailwind CSS

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] Tailwind setup and working
```

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
