### ISSUE TITLE
⚙️Setup renovate

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/blog#9]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Setup renovate

### Acceptance Criteria

- [x] Renovate dependency management configured

### ToDo Items

- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
[run-sync]
